fastlane_version "2.24.0"

before_all do
  Dir.chdir('..') do
    sh "carthage bootstrap --platform ios,mac --cache-builds"
  end
end

desc "Runs all the tests"
lane :test do
  scan(scheme: "SwiftOpenStreetMac")
  scan(scheme: "SwiftOpenStreetMap")
end

